#!flask/bin/python
from flask import Flask, request, make_response, jsonify, Response
from flask_restful import Resource, Api
from sqlalchemy import create_engine
from json import dumps

e = create_engine('sqlite:////var/www/api/api/baseball.db')

app = Flask(__name__)
api = Api(app)


# Returns JSON containing all years on record
class PlayerList(Resource):
    def get(self):
        conn = e.connect()
        query = conn.execute("select distinct playerID from master")
        data ={'data':[i[0] for i in query.cursor.fetchall()]}
        dump = dumps(data)
        response =  Response(dump, status=201, mimetype='application/json')
        response.headers['Access-Control-Allow-Origin'] = '*'
        return response

# Returns a JSON of all stat categories
class Player(Resource):
    def get(self, playerID):
        conn = e.connect()
        query = conn.execute("select * from batters where playerID=(?)", (playerID,))
        data = {'data':[dict(zip(tuple (query.keys()), i)) for i in query.cursor]}
        dump = dumps(data)

        response =  Response(dump, status=201, mimetype='application/json') 
        response.headers['Access-Control-Allow-Origin'] = '*'
        return response

# Returns JSON containing all players and their respective stats.
class PlayerYear(Resource):
    def get(self, playerID, yearID):
        conn = e.connect()
        query = conn.execute("select * from batters where yearID=(?) and playerID=(?)", (yearID, playerID))
        data = {'data':[dict(zip(tuple (query.keys()), i)) for i in query.cursor]}
        dump = dumps(data)
        response =  Response(dump, status=200, mimetype='application.json')
        response.headers['Access-Control-Allow-Origin'] = '*'
        return response


class Year_Batter(Resource):
    def get(self, yearID, category, playerID):
        conn = e.connect()
        query = conn.execute("select * from {0} where yearID=(?) and playerID=(?)".format(category), (yearID, playerID))
        data = {'data': [dict(zip(tuple (query.keys()), i)) for i in query.cursor]} 
        dump = dumps(data)
        response = Response(dump, status=200, mimetype='application.json')
        response.headers['Access-Control-Allow-Origin'] = '*'
        return response

api.add_resource(PlayerList, '/api/v1.0/players/')
api.add_resource(Player, '/api/v1.0/players/<string:playerID>/')
api.add_resource(PlayerYear, '/api/v1.0/players/<string:playerID>/<string:yearID>/')
api.add_resource(Year_Batter, '/years/<string:yearID>/<string:category>/<string:playerID>/')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
